=== sammko/data/schemas/event.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://kockatykalendar.sk/v0.0.3/event.schema.json",
  "title": "Event",
  "description": "An event in the calendar",
  "type": "object",
  "properties": {
    "name": {
      "description": "Name of the event",
      "type": "string"
    },
    "sciences": {
      "description": "Event sciences",
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["mat", "fyz", "inf", "other"]
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "type": {
      "description": "Event type",
      "type": "string",
      "enum": ["sutaz", "seminar", "sustredenie", "vikendovka", "tabor", "olympiada", "prednasky"]
    },
    "date": {
      "description": "Date information",
      "type": "object",
      "properties": {
        "start": {
          "description": "Event date or start date if more days",
          "type": "string",
          "format": "date"
        },
        "end": {
          "description": "End date",
          "type": "string",
          "format": "date"
        },
        "text": {
          "description": "Event date for user",
          "type": "string"
        }
      },
      "required": ["start"]
    },
    "organizers": {
      "description": "Organizer or list of organizers",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "link": {
      "description": "Link to more information",
      "type": "string",
      "format": "uri"
    },
    "places": {
      "description": "Place where the event is organized",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "contestants": {
      "description": "Contestant information",
      "type": "object",
      "properties": {
        "min": {
          "description": "Min class to attend",
          "type": "string",
          "pattern": "^(zs[1-9]|ss[1-4])$"
        },
        "max": {
          "description": "Max class to attend",
          "type": "string",
          "pattern": "^(zs[1-9]|ss[1-4])$"
        }
      },
      "required": ["min"]
    },
    "info": {
      "description": "Short description of event",
      "type": "string",
      "maxLength": 255
    },
    "color": {
      "description": "Override default color based on first science",
      "type": "string",
      "anyOf": [
        { "enum": ["red", "orange", "yellow", "green", "blue", "purple"] },
        { "pattern": "^#([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$"}
      ]
    },
    "volatile": {
        "description": "If true event may not take place",
        "type": "boolean"
    },
    "notifications": {
      "description": "Notification settings",
      "type": "object",
      "properties": {
        "remind_days_before": {
          "description": "How many days before should we notify people",
          "type": "array",
          "items": {
            "type": "number"
          }
        }
      },
      "required": ["remind_days_before"]
    }
  },
  "required": [ "name", "sciences", "type", "date", "organizers", "places", "contestants" ]
}

=== sammko/data/2019_20.json
[{"name": "1. s\u00e9ria KMS", "type": "seminar", "sciences": ["mat"], "date": {"start": "2019-09-01", "end": "2019-09-30", "text": "september"}, "contestants": {"min": "ss1", "max": "ss4"}, "places": ["cel\u00e9 Slovensko"], "organizers": ["trojsten"], "link": "https://kms.sk/"}, {"name": "3. s\u00e9ria Pikomatu", "type": "seminar", "sciences": ["mat"], "date": {"start": "2019-11-01", "end": "2019-12-02", "text": "november-december"}, "contestants": {"min": "zs5", "max": "zs9"}, "places": ["cel\u00e9 Slovensko"], "organizers": ["p-mat"], "link": "https://pikomat.sk/"}, {"name": "1. s\u00e9ria KSP", "type": "seminar", "sciences": ["inf"], "date": {"start": "2019-09-01", "end": "2019-10-21", "text": "september-okt\u00f3ber"}, "contestants": {"min": "ss1", "max": "ss4"}, "places": ["cel\u00e9 Slovensko"], "organizers": ["trojsten"], "link": "https://ksp.sk/"}, {"name": "2. s\u00e9ria KMS", "type": "seminar", "sciences": ["mat"], "date": {"start": "2019-10-01", "end": "2019-10-28", "text": "okt\u00f3ber"}, "contestants": {"min": "ss1", "max": "ss4"}, "places": ["cel\u00e9 Slovensko"], "organizers": ["trojsten"], "link": "https://kms.sk/"}, {"name": "1. s\u00e9ria FKS", "type": "seminar", "sciences": ["fyz"], "date": {"start": "2019-10-01", "end": "2019-11-04", "text": "okt\u00f3ber-november"}, "contestants": {"min": "ss1", "max": "ss4"}, "places": ["cel\u00e9 Slovensko"], "organizers": ["trojsten"], "link": "https://fks.sk/"}, {"name": "2. s\u00e9ria Matik", "type": "seminar", "sciences": ["mat"], "date": {"start": "2019-11-01", "end": "2019-11-25", "text": "november"}, "contestants": {"min": "zs7", "max": "zs9"}, "places": ["cel\u00e9 Slovensko"], "organizers": ["strom"], "link": "https://matik.strom.sk/"}, {"name": "2. s\u00e9ria Sezamu", "type": "seminar", "sciences": ["mat"], "date": {"start": "2019-10-01", "end": "2019-11-04", "text": "okt\u00f3ber-november"}, "contestants": {"min": "zs7", "max": "zs9"}, "places": ["cel\u00e9 Slovensko"], "organizers": ["sezam"], "link": "https://www.sezam.sk/sezam/"}, {"name": "2. s\u00e9ria Pikofyzu", "type": "seminar", "sciences": ["fyz"], "date": {"start": "2019-10-01", "end": "2019-10-28", "text": "okt\u00f3ber"}, "contestants": {"min": "zs7", "max": "zs9"}, "places": ["cel\u00e9 Slovensko"], "organizers": ["p-mat"], "link": "https://pikofyz.sk/"}, {"name": "1. s\u00e9ria Malyn\u00e1r", "type": "seminar", "sciences": ["mat"], "date": {"start": "2019-09-01", "end": "2019-10-21", "text": "september-okt\u00f3ber"}, "contestants": {"min": "zs4", "max": "zs6"}, "places": ["cel\u00e9 Slovensko"], "organizers": ["strom"], "link": "https://malynar.strom.sk/"}, {"name": "2. s\u00e9ria STROM", "type": "seminar", "sciences": ["mat"], "date": {"start": "2019-11-01", "end": "2019-11-02", "text": "november-december"}, "contestants": {"min": "ss1", "max": "ss4"}, "places": ["cel\u00e9 Slovensko"], "organizers": ["strom"], "link": "https://seminar.strom.sk/"}, {"name": "1. s\u00e9ria Pikofyzu", "type": "seminar", "sciences": ["fyz"], "date": {"start": "2019-09-01", "end": "2019-09-30", "text": "september"}, "contestants": {"min": "zs7", "max": "zs9"}, "places": ["cel\u00e9 Slovensko"], "organizers": ["p-mat"], "link": "https://pikofyz.sk/"}, {"name": "2. s\u00e9ria FKS", "type": "seminar", "sciences": ["fyz"], "date": {"start": "2019-11-01", "end": "2019-12-02", "text": "november-december"}, "contestants": {"min": "ss1", "max": "ss4"}, "places": ["cel\u00e9 Slovensko"], "organizers": ["trojsten"], "link": "https://fks.sk/"}, {"name": "3. s\u00e9ria Pikofyzu", "type": "seminar", "sciences": ["fyz"], "date": {"start": "2019-11-01", "end": "2019-12-02", "text": "november-december"}, "contestants": {"min": "zs7", "max": "zs9"}, "places": ["cel\u00e9 Slovensko"], "organizers": ["p-mat"], "link": "https://pikofyz.sk/"}, {"name": "2. s\u00e9ria Pikomatu", "type": "seminar", "sciences": ["mat"], "date": {"start": "2019-10-01", "end": "2019-10-28", "text": "okt\u00f3ber"}, "contestants": {"min": "zs5", "max": "zs9"}, "places": ["cel\u00e9 Slovensko"], "organizers": ["p-mat"], "link": "https://pikomat.sk/"}, {"name": "1. s\u00e9ria Sezamu", "type": "seminar", "sciences": ["mat"], "date": {"start": "2019-09-01", "end": "2019-09-30", "text": "september"}, "contestants": {"min": "zs7", "max": "zs9"}, "places": ["cel\u00e9 Slovensko"], "organizers": ["sezam"], "link": "https://www.sezam.sk/sezam/"}, {"name": "1. s\u00e9ria STROM", "type": "seminar", "sciences": ["mat"], "date": {"start": "2019-09-01", "end": "2019-10-28", "text": "september-okt\u00f3ber"}, "contestants": {"min": "ss1", "max": "ss4"}, "places": ["cel\u00e9 Slovensko"], "organizers": ["strom"], "link": "https://seminar.strom.sk/"}, {"name": "1. s\u00e9ria Matik", "type": "seminar", "sciences": ["mat"], "date": {"start": "2019-09-01", "end": "2019-10-21", "text": "september-okt\u00f3ber"}, "contestants": {"min": "zs7", "max": "zs9"}, "places": ["cel\u00e9 Slovensko"], "organizers": ["strom"], "link": "https://matik.strom.sk/"}, {"name": "1. s\u00e9ria Prask", "type": "seminar", "sciences": ["inf"], "date": {"start": "2019-10-01", "end": "2019-11-18", "text": "okt\u00f3ber-november"}, "contestants": {"min": "zs7", "max": "zs9"}, "places": ["cel\u00e9 Slovensko"], "organizers": ["trojsten"], "link": "https://prask.ksp.sk/"}, {"name": "3. s\u00e9ria KMS", "type": "seminar", "sciences": ["mat"], "date": {"start": "2019-11-01", "end": "2019-11-25", "text": "november"}, "contestants": {"min": "ss1", "max": "ss4"}, "places": ["cel\u00e9 Slovensko"], "organizers": ["trojsten"], "link": "https://kms.sk/"}, {"name": "2. s\u00e9ria Sezamko", "type": "seminar", "sciences": ["mat"], "date": {"start": "2019-10-01", "end": "2019-11-04", "text": "okt\u00f3ber-november"}, "contestants": {"min": "zs5", "max": "zs6"}, "places": ["cel\u00e9 Slovensko"], "organizers": ["sezam"], "link": "https://www.sezam.sk/sezamko/"}, {"name": "3. s\u00e9ria UFO", "type": "seminar", "sciences": ["fyz"], "date": {"start": "2019-12-01", "end": "2020-01-13", "text": "december-janu\u00e1r"}, "contestants": {"min": "zs7", "max": "zs9"}, "places": ["cel\u00e9 Slovensko"], "organizers": ["trojsten"], "link": "https://ufo.fks.sk/"}, {"name": "2. s\u00e9ria Prask", "type": "seminar", "sciences": ["inf"], "date": {"start": "2019-12-01", "end": "2020-01-07", "text": "december-janu\u00e1r"}, "contestants": {"min": "zs7", "max": "zs9"}, "places": ["cel\u00e9 Slovensko"], "organizers": ["trojsten"], "link": "https://prask.ksp.sk/"}, {"name": "2. s\u00e9ria Rie\u0161ok", "type": "seminar", "sciences": ["mat"], "date": {"start": "2019-10-01", "end": "2019-11-04", "text": "okt\u00f3ber-november"}, "contestants": {"min": "zs5", "max": "zs9"}, "places": ["cel\u00e9 Slovensko"], "organizers": ["riesky"], "link": "https://riesky.sk/"}, {"name": "1. s\u00e9ria Pikomatu", "type": "seminar", "sciences": ["mat"], "date": {"start": "2019-09-01", "end": "2019-09-30", "text": "september"}, "contestants": {"min": "zs5", "max": "zs9"}, "places": ["cel\u00e9 Slovensko"], "organizers": ["p-mat"], "link": "https://pikomat.sk/"}, {"name": "1. s\u00e9ria Rie\u0161ok", "type": "seminar", "sciences": ["mat"], "date": {"start": "2019-09-01", "end": "2019-10-07", "text": "september-okt\u00f3ber"}, "contestants": {"min": "zs5", "max": "zs9"}, "places": ["cel\u00e9 Slovensko"], "organizers": ["riesky"], "link": "https://riesky.sk/"}, {"name": "2. s\u00e9ria KSP", "type": "seminar", "sciences": ["inf"], "date": {"start": "2019-12-01", "end": "2020-01-13", "text": "december-janu\u00e1r"}, "contestants": {"min": "ss1", "max": "ss4"}, "places": ["cel\u00e9 Slovensko"], "organizers": ["trojsten"], "link": "https://ksp.sk/"}, {"name": "2. s\u00e9ria UFO", "type": "seminar", "sciences": ["fyz"], "date": {"start": "2019-11-01", "end": "2019-12-09", "text": "november-december"}, "contestants": {"min": "zs7", "max": "zs9"}, "places": ["cel\u00e9 Slovensko"], "organizers": ["trojsten"], "link": "https://ufo.fks.sk/"}, {"name": "1. s\u00e9ria Sezamko", "type": "seminar", "sciences": ["mat"], "date": {"start": "2019-09-01", "end": "2019-09-30", "text": "september"}, "contestants": {"min": "zs5", "max": "zs6"}, "places": ["cel\u00e9 Slovensko"], "organizers": ["sezam"], "link": "https://www.sezam.sk/sezamko/"}, {"name": "3. s\u00e9ria Sezamu", "type": "seminar", "sciences": ["mat"], "date": {"start": "2019-12-01", "end": "2020-01-07", "text": "december-janu\u00e1r"}, "contestants": {"min": "zs7", "max": "zs9"}, "places": ["cel\u00e9 Slovensko"], "organizers": ["sezam"], "link": "https://www.sezam.sk/sezam/"}, {"name": "2. s\u00e9ria Malyn\u00e1r", "type": "seminar", "sciences": ["mat"], "date": {"start": "2019-11-01", "end": "2019-11-25", "text": "november"}, "contestants": {"min": "zs4", "max": "zs6"}, "places": ["cel\u00e9 Slovensko"], "organizers": ["strom"], "link": "https://malynar.strom.sk/"}, {"name": "1. s\u00e9ria UFO", "type": "seminar", "sciences": ["fyz"], "date": {"start": "2019-09-01", "end": "2019-10-21", "text": "september-okt\u00f3ber"}, "contestants": {"min": "zs7", "max": "zs9"}, "places": ["cel\u00e9 Slovensko"], "organizers": ["trojsten"], "link": "https://ufo.fks.sk/"}, {"name": "3. s\u00e9ria Rie\u0161ok", "type": "seminar", "sciences": ["mat"], "date": {"start": "2019-11-01", "end": "2019-12-02", "text": "november-december"}, "contestants": {"min": "zs5", "max": "zs9"}, "places": ["cel\u00e9 Slovensko"], "organizers": ["riesky"], "link": "https://riesky.sk/"}, {"name": "Kockat\u00fd v\u00edkend", "type": "vikendovka", "sciences": ["mat", "fyz"], "date": {"start": "2019-11-15", "end": "2019-11-17"}, "contestants": {"min": "zs5", "max": "zs9"}, "places": ["\u0160vP po celom Slovensku"], "organizers": ["p-mat"], "link": "https://p-mat.sk/aktivity/kockaty"}, {"name": "Klub Trojstenu", "type": "vikendovka", "sciences": ["mat", "fyz", "inf"], "date": {"start": "2019-11-09", "end": "2019-11-10"}, "contestants": {"min": "ss1", "max": "ss4"}, "places": ["Bratislava"], "organizers": ["trojsten"], "link": "http
